In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

data = pd.read_csv('processed_data.csv')

In [2]:
patient_counts = data['patient_id'].value_counts()
patient_counts_pd = pd.DataFrame(patient_counts)
patient_counts_pd = patient_counts_pd.loc[patient_counts_pd['count'] > 29]

filtered_data = data[data['patient_id'].isin(patient_counts_pd.index)]  # 해당 ID만 남기기
filtered_data.to_csv('filtered_id_data.csv')

In [3]:
threshold_high = 25.34 

threshold_low = -2.61

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import confusion_matrix, classification_report
import pandas as pd

labels = ['bad', 'mid', 'good']

for pid, group in filtered_data.groupby('patient_id'):

    # feature / target 나누기
    y = group['score_level']
    X = group.drop(columns=['sleep_quality_score', 'score_level', 'patient_id', 'timestamp'])
    

    # train/test split (시계열 고려해서 shuffle=False)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, shuffle=False
    )


    # 모델 정의
    clf = DecisionTreeClassifier(max_depth=6, random_state=42)
    clf.fit(X_train, y_train)

    # 예측
    y_pred = clf.predict(X_test)

    # 평가
    print(confusion_matrix(y_test, y_pred, labels=labels))
    print(classification_report(y_test, y_pred, labels=labels))



[[ 1  1  1]
 [ 8 71  4]
 [ 2  9  6]]
              precision    recall  f1-score   support

         bad       0.09      0.33      0.14         3
         mid       0.88      0.86      0.87        83
        good       0.55      0.35      0.43        17

    accuracy                           0.76       103
   macro avg       0.50      0.51      0.48       103
weighted avg       0.80      0.76      0.77       103

[[ 1  7 20]
 [ 5 51 60]
 [ 1 12 76]]
              precision    recall  f1-score   support

         bad       0.14      0.04      0.06        28
         mid       0.73      0.44      0.55       116
        good       0.49      0.85      0.62        89

    accuracy                           0.55       233
   macro avg       0.45      0.44      0.41       233
weighted avg       0.57      0.55      0.52       233

[[ 10  13   8]
 [ 19  45  39]
 [  1  58 111]]
              precision    recall  f1-score   support

         bad       0.33      0.32      0.33        31
         

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

              precision    recall  f1-score   support

         bad       0.66      0.55      0.60        77
         mid       0.56      0.73      0.64        79
        good       0.12      0.07      0.09        27

    accuracy                           0.56       183
   macro avg       0.45      0.45      0.44       183
weighted avg       0.54      0.56      0.54       183

[[ 4  4  3]
 [ 6 45  4]
 [ 5 18  5]]
              precision    recall  f1-score   support

         bad       0.27      0.36      0.31        11
         mid       0.67      0.82      0.74        55
        good       0.42      0.18      0.25        28

    accuracy                           0.57        94
   macro avg       0.45      0.45      0.43        94
weighted avg       0.55      0.57      0.54        94

[[ 9  6  2]
 [ 7 70  8]
 [ 6 14 15]]
              precision    recall  f1-score   support

         bad       0.41      0.53      0.46        17
         mid       0.78      0.82      0.80        85
 

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

[[1 3 1]
 [2 5 1]
 [0 0 0]]
              precision    recall  f1-score   support

         bad       0.33      0.20      0.25         5
         mid       0.62      0.62      0.62         8
        good       0.00      0.00      0.00         0

    accuracy                           0.46        13
   macro avg       0.32      0.27      0.29        13
weighted avg       0.51      0.46      0.48        13

[[3 1 3]
 [1 5 1]
 [0 2 0]]
              precision    recall  f1-score   support

         bad       0.75      0.43      0.55         7
         mid       0.62      0.71      0.67         7
        good       0.00      0.00      0.00         2

    accuracy                           0.50        16
   macro avg       0.46      0.38      0.40        16
weighted avg       0.60      0.50      0.53        16

[[96  3  2]
 [ 4 71  0]
 [ 0  0  0]]
              precision    recall  f1-score   support

         bad       0.96      0.95      0.96       101
         mid       0.96      0.95   

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\User

[[ 6  7  1]
 [ 3 51  5]
 [ 1 13  4]]
              precision    recall  f1-score   support

         bad       0.60      0.43      0.50        14
         mid       0.72      0.86      0.78        59
        good       0.40      0.22      0.29        18

    accuracy                           0.67        91
   macro avg       0.57      0.51      0.52        91
weighted avg       0.64      0.67      0.64        91

[[ 0  0  0]
 [ 0 18  0]
 [ 0  0  0]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         0
         mid       1.00      1.00      1.00        18
        good       0.00      0.00      0.00         0

    accuracy                           1.00        18
   macro avg       0.33      0.33      0.33        18
weighted avg       1.00      1.00      1.00        18

[[ 5  2  2]
 [ 4 19  1]
 [ 1  2  7]]
              precision    recall  f1-score   support

         bad       0.50      0.56      0.53         9
         mid      

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is

[[ 3  5  4]
 [13 43 16]
 [33 60 41]]
              precision    recall  f1-score   support

         bad       0.06      0.25      0.10        12
         mid       0.40      0.60      0.48        72
        good       0.67      0.31      0.42       134

    accuracy                           0.40       218
   macro avg       0.38      0.38      0.33       218
weighted avg       0.55      0.40      0.42       218

[[ 5 20  2]
 [ 4 47  6]
 [ 1 64  3]]
              precision    recall  f1-score   support

         bad       0.50      0.19      0.27        27
         mid       0.36      0.82      0.50        57
        good       0.27      0.04      0.08        68

    accuracy                           0.36       152
   macro avg       0.38      0.35      0.28       152
weighted avg       0.35      0.36      0.27       152

[[83  5  1]
 [ 0 59  0]
 [ 0  0  0]]


C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


              precision    recall  f1-score   support

         bad       1.00      0.93      0.97        89
         mid       0.92      1.00      0.96        59
        good       0.00      0.00      0.00         0

    accuracy                           0.96       148
   macro avg       0.64      0.64      0.64       148
weighted avg       0.97      0.96      0.96       148

[[ 2  3  2]
 [ 7 28  6]
 [ 4  4 20]]
              precision    recall  f1-score   support

         bad       0.15      0.29      0.20         7
         mid       0.80      0.68      0.74        41
        good       0.71      0.71      0.71        28

    accuracy                           0.66        76
   macro avg       0.56      0.56      0.55        76
weighted avg       0.71      0.66      0.68        76

[[66 22  6]
 [40 42  8]
 [ 4  0  1]]
              precision    recall  f1-score   support

         bad       0.60      0.70      0.65        94
         mid       0.66      0.47      0.55        90
 

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is

[[61  7  0]
 [19 47  0]
 [ 1  3  0]]
              precision    recall  f1-score   support

         bad       0.75      0.90      0.82        68
         mid       0.82      0.71      0.76        66
        good       0.00      0.00      0.00         4

    accuracy                           0.78       138
   macro avg       0.53      0.54      0.53       138
weighted avg       0.77      0.78      0.77       138

[[ 8  5  1]
 [12 42 17]
 [ 0  1  3]]
              precision    recall  f1-score   support

         bad       0.40      0.57      0.47        14
         mid       0.88      0.59      0.71        71
        good       0.14      0.75      0.24         4

    accuracy                           0.60        89
   macro avg       0.47      0.64      0.47        89
weighted avg       0.77      0.60      0.65        89

[[0 7 0]
 [2 4 0]
 [0 0 0]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         7
         mid       0.36    

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

[[ 0  1  0]
 [ 0 24  0]
 [ 0  0  0]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         1
         mid       0.96      1.00      0.98        24
        good       0.00      0.00      0.00         0

    accuracy                           0.96        25
   macro avg       0.32      0.33      0.33        25
weighted avg       0.92      0.96      0.94        25

[[ 0  1  1]
 [ 3  9 16]
 [ 0  7  3]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         2
         mid       0.53      0.32      0.40        28
        good       0.15      0.30      0.20        10

    accuracy                           0.30        40
   macro avg       0.23      0.21      0.20        40
weighted avg       0.41      0.30      0.33        40

[[ 2  1  1]
 [ 0 12  1]
 [ 1  2  0]]
              precision    recall  f1-score   support

         bad       0.67      0.50      0.57         4
         mid      

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is

              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         1
         mid       0.71      0.77      0.74        13
        good       0.00      0.00      0.00         3

    accuracy                           0.59        17
   macro avg       0.24      0.26      0.25        17
weighted avg       0.55      0.59      0.57        17

[[  6  14   4]
 [ 14 137  16]
 [  2  14   6]]
              precision    recall  f1-score   support

         bad       0.27      0.25      0.26        24
         mid       0.83      0.82      0.83       167
        good       0.23      0.27      0.25        22

    accuracy                           0.70       213
   macro avg       0.44      0.45      0.45       213
weighted avg       0.71      0.70      0.70       213

[[ 0  9  1]
 [ 0 14  1]
 [ 0  6  1]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00        10
         mid       0.48      0.93      0.64   

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

[[ 2  2  0]
 [ 2 13  0]
 [ 0  0  0]]
              precision    recall  f1-score   support

         bad       0.50      0.50      0.50         4
         mid       0.87      0.87      0.87        15
        good       0.00      0.00      0.00         0

    accuracy                           0.79        19
   macro avg       0.46      0.46      0.46        19
weighted avg       0.79      0.79      0.79        19

[[0 3 1]
 [3 4 6]
 [2 0 7]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         4
         mid       0.57      0.31      0.40        13
        good       0.50      0.78      0.61         9

    accuracy                           0.42        26
   macro avg       0.36      0.36      0.34        26
weighted avg       0.46      0.42      0.41        26

[[ 9  6  4]
 [ 3 51  7]
 [ 3  2 13]]
              precision    recall  f1-score   support

         bad       0.60      0.47      0.53        19
         mid       0.86    

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\User

[[ 6 11  7]
 [ 5  5  4]
 [ 1  2  2]]
              precision    recall  f1-score   support

         bad       0.50      0.25      0.33        24
         mid       0.28      0.36      0.31        14
        good       0.15      0.40      0.22         5

    accuracy                           0.30        43
   macro avg       0.31      0.34      0.29        43
weighted avg       0.39      0.30      0.31        43

[[ 2  7  0]
 [ 0 27  0]
 [ 0  1  0]]
              precision    recall  f1-score   support

         bad       1.00      0.22      0.36         9
         mid       0.77      1.00      0.87        27
        good       0.00      0.00      0.00         1

    accuracy                           0.78        37
   macro avg       0.59      0.41      0.41        37
weighted avg       0.81      0.78      0.72        37

[[ 1  0  2]
 [ 0 33 10]
 [ 0  4  3]]
              precision    recall  f1-score   support

         bad       1.00      0.33      0.50         3
         mid      

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


[[27 40  0]
 [19 87  0]
 [ 3  5  0]]
              precision    recall  f1-score   support

         bad       0.55      0.40      0.47        67
         mid       0.66      0.82      0.73       106
        good       0.00      0.00      0.00         8

    accuracy                           0.63       181
   macro avg       0.40      0.41      0.40       181
weighted avg       0.59      0.63      0.60       181

[[ 0  3  2]
 [ 0 12  7]
 [ 0  4 11]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         5
         mid       0.63      0.63      0.63        19
        good       0.55      0.73      0.63        15

    accuracy                           0.59        39
   macro avg       0.39      0.45      0.42        39
weighted avg       0.52      0.59      0.55        39

[[ 2  7  2]
 [ 8 25 10]
 [ 1 12 60]]
              precision    recall  f1-score   support

         bad       0.18      0.18      0.18        11
         mid      

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

[[64  5  2]
 [15 18  2]
 [ 2  4  0]]
              precision    recall  f1-score   support

         bad       0.79      0.90      0.84        71
         mid       0.67      0.51      0.58        35
        good       0.00      0.00      0.00         6

    accuracy                           0.73       112
   macro avg       0.49      0.47      0.47       112
weighted avg       0.71      0.73      0.72       112

[[ 5  4 11]
 [ 5 28 23]
 [ 4  9 30]]
              precision    recall  f1-score   support

         bad       0.36      0.25      0.29        20
         mid       0.68      0.50      0.58        56
        good       0.47      0.70      0.56        43

    accuracy                           0.53       119
   macro avg       0.50      0.48      0.48       119
weighted avg       0.55      0.53      0.52       119

[[ 5  9  0]
 [ 9 41 16]
 [10 43 29]]
              precision    recall  f1-score   support

         bad       0.21      0.36      0.26        14
         mid      

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

[[ 4  0  1]
 [ 1 43  0]
 [ 0  2  0]]
              precision    recall  f1-score   support

         bad       0.80      0.80      0.80         5
         mid       0.96      0.98      0.97        44
        good       0.00      0.00      0.00         2

    accuracy                           0.92        51
   macro avg       0.59      0.59      0.59        51
weighted avg       0.90      0.92      0.91        51

[[ 2  0  0]
 [ 0 15  0]
 [ 0  0  0]]
              precision    recall  f1-score   support

         bad       1.00      1.00      1.00         2
         mid       1.00      1.00      1.00        15
        good       0.00      0.00      0.00         0

    accuracy                           1.00        17
   macro avg       0.67      0.67      0.67        17
weighted avg       1.00      1.00      1.00        17

[[0 0 0]
 [1 4 7]
 [1 2 1]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         0
         mid       0.67    

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is

[[ 5  7 24]
 [10 32 27]
 [13 12 45]]
              precision    recall  f1-score   support

         bad       0.18      0.14      0.16        36
         mid       0.63      0.46      0.53        69
        good       0.47      0.64      0.54        70

    accuracy                           0.47       175
   macro avg       0.42      0.42      0.41       175
weighted avg       0.47      0.47      0.46       175

[[ 4  6  8]
 [ 3 25 32]
 [ 3  3 47]]
              precision    recall  f1-score   support

         bad       0.40      0.22      0.29        18
         mid       0.74      0.42      0.53        60
        good       0.54      0.89      0.67        53

    accuracy                           0.58       131
   macro avg       0.56      0.51      0.50       131
weighted avg       0.61      0.58      0.55       131

[[22  2  1]
 [ 4 35  0]
 [ 0  0  0]]


C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\User

              precision    recall  f1-score   support

         bad       0.85      0.88      0.86        25
         mid       0.95      0.90      0.92        39
        good       0.00      0.00      0.00         0

    accuracy                           0.89        64
   macro avg       0.60      0.59      0.59        64
weighted avg       0.91      0.89      0.90        64

[[17 42  4]
 [ 3 23 14]
 [ 1  1  7]]
              precision    recall  f1-score   support

         bad       0.81      0.27      0.40        63
         mid       0.35      0.57      0.43        40
        good       0.28      0.78      0.41         9

    accuracy                           0.42       112
   macro avg       0.48      0.54      0.42       112
weighted avg       0.60      0.42      0.42       112

[[ 0  0  0]
 [ 0 13  2]
 [ 0  3  4]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         0
         mid       0.81      0.87      0.84        15
 

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is

[[ 1  1  4]
 [ 0 30  1]
 [ 0  0  5]]
              precision    recall  f1-score   support

         bad       1.00      0.17      0.29         6
         mid       0.97      0.97      0.97        31
        good       0.50      1.00      0.67         5

    accuracy                           0.86        42
   macro avg       0.82      0.71      0.64        42
weighted avg       0.92      0.86      0.83        42

[[ 6 13  5]
 [12 37  7]
 [ 6  8  2]]
              precision    recall  f1-score   support

         bad       0.25      0.25      0.25        24
         mid       0.64      0.66      0.65        56
        good       0.14      0.12      0.13        16

    accuracy                           0.47        96
   macro avg       0.34      0.35      0.34        96
weighted avg       0.46      0.47      0.46        96

[[12 16  7]
 [ 4 44  3]
 [ 5  7  3]]
              precision    recall  f1-score   support

         bad       0.57      0.34      0.43        35
         mid      

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


[[ 2  2  8]
 [ 3 28  5]
 [ 2  2  0]]
              precision    recall  f1-score   support

         bad       0.29      0.17      0.21        12
         mid       0.88      0.78      0.82        36
        good       0.00      0.00      0.00         4

    accuracy                           0.58        52
   macro avg       0.39      0.31      0.34        52
weighted avg       0.67      0.58      0.62        52

[[ 7 14  5]
 [ 5 43  0]
 [ 2  5  1]]
              precision    recall  f1-score   support

         bad       0.50      0.27      0.35        26
         mid       0.69      0.90      0.78        48
        good       0.17      0.12      0.14         8

    accuracy                           0.62        82
   macro avg       0.45      0.43      0.42        82
weighted avg       0.58      0.62      0.58        82

[[ 7  3  2]
 [ 2 16  1]
 [ 1  2  1]]
              precision    recall  f1-score   support

         bad       0.70      0.58      0.64        12
         mid      

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

              precision    recall  f1-score   support

         bad       0.50      0.40      0.44        40
         mid       0.59      0.73      0.65        67
        good       0.29      0.21      0.24        29

    accuracy                           0.52       136
   macro avg       0.46      0.45      0.45       136
weighted avg       0.50      0.52      0.50       136

[[0 2 2]
 [0 9 3]
 [0 1 2]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         4
         mid       0.75      0.75      0.75        12
        good       0.29      0.67      0.40         3

    accuracy                           0.58        19
   macro avg       0.35      0.47      0.38        19
weighted avg       0.52      0.58      0.54        19

[[ 0  1  0]
 [ 2 11  0]
 [ 0  0  0]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         1
         mid       0.92      0.85      0.88        13
        go

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is

[[ 6 18  2]
 [ 8 40 12]
 [ 3  8  3]]
              precision    recall  f1-score   support

         bad       0.35      0.23      0.28        26
         mid       0.61      0.67      0.63        60
        good       0.18      0.21      0.19        14

    accuracy                           0.49       100
   macro avg       0.38      0.37      0.37       100
weighted avg       0.48      0.49      0.48       100

[[ 4  3  0]
 [ 7 23  1]
 [ 2  5  1]]
              precision    recall  f1-score   support

         bad       0.31      0.57      0.40         7
         mid       0.74      0.74      0.74        31
        good       0.50      0.12      0.20         8

    accuracy                           0.61        46
   macro avg       0.52      0.48      0.45        46
weighted avg       0.63      0.61      0.60        46

[[ 1  3  0]
 [ 1 10  0]
 [ 0  1  0]]
              precision    recall  f1-score   support

         bad       0.50      0.25      0.33         4
         mid      

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

              precision    recall  f1-score   support

         bad       0.44      0.30      0.36        27
         mid       0.39      0.30      0.34        30
        good       0.13      0.43      0.20         7

    accuracy                           0.31        64
   macro avg       0.32      0.34      0.30        64
weighted avg       0.39      0.31      0.33        64

[[ 0  0  2]
 [ 0  3  2]
 [ 0  2 13]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         2
         mid       0.60      0.60      0.60         5
        good       0.76      0.87      0.81        15

    accuracy                           0.73        22
   macro avg       0.45      0.49      0.47        22
weighted avg       0.66      0.73      0.69        22

[[ 0  0  0]
 [ 1 21  0]
 [ 0  0  0]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         0
         mid       1.00      0.95      0.98        22
 

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

[[ 0  0  0]
 [ 8  2  3]
 [ 1  0 12]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         0
         mid       1.00      0.15      0.27        13
        good       0.80      0.92      0.86        13

    accuracy                           0.54        26
   macro avg       0.60      0.36      0.37        26
weighted avg       0.90      0.54      0.56        26

[[47 13  8]
 [14 25  1]
 [ 1  0  0]]
              precision    recall  f1-score   support

         bad       0.76      0.69      0.72        68
         mid       0.66      0.62      0.64        40
        good       0.00      0.00      0.00         1

    accuracy                           0.66       109
   macro avg       0.47      0.44      0.45       109
weighted avg       0.71      0.66      0.69       109

[[ 1  1  0]
 [ 1 18  0]
 [ 0  1  0]]
              precision    recall  f1-score   support

         bad       0.50      0.50      0.50         2
         mid      

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\User

[[0 3 0]
 [0 4 0]
 [0 0 0]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         3
         mid       0.57      1.00      0.73         4
        good       0.00      0.00      0.00         0

    accuracy                           0.57         7
   macro avg       0.19      0.33      0.24         7
weighted avg       0.33      0.57      0.42         7

[[ 1  8  2]
 [ 6 12 26]
 [ 8 21 47]]
              precision    recall  f1-score   support

         bad       0.07      0.09      0.08        11
         mid       0.29      0.27      0.28        44
        good       0.63      0.62      0.62        76

    accuracy                           0.46       131
   macro avg       0.33      0.33      0.33       131
weighted avg       0.47      0.46      0.46       131

[[0 0 0]
 [1 7 2]
 [1 0 6]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         0
         mid       1.00      0.70   

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is

[[ 1  4  2]
 [ 6 45 27]
 [ 0 17 17]]
              precision    recall  f1-score   support

         bad       0.14      0.14      0.14         7
         mid       0.68      0.58      0.62        78
        good       0.37      0.50      0.42        34

    accuracy                           0.53       119
   macro avg       0.40      0.41      0.40       119
weighted avg       0.56      0.53      0.54       119

[[ 0  0  0]
 [ 0 10  0]
 [ 0  0  0]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         0
         mid       1.00      1.00      1.00        10
        good       0.00      0.00      0.00         0

    accuracy                           1.00        10
   macro avg       0.33      0.33      0.33        10
weighted avg       1.00      1.00      1.00        10

[[ 2  4  6]
 [ 4 13 25]
 [ 4 17 41]]
              precision    recall  f1-score   support

         bad       0.20      0.17      0.18        12
         mid      

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is

              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         0
         mid       1.00      1.00      1.00       111
        good       0.00      0.00      0.00         0

    accuracy                           1.00       111
   macro avg       0.33      0.33      0.33       111
weighted avg       1.00      1.00      1.00       111

[[14  5 10]
 [ 7 12 14]
 [ 2  1  2]]
              precision    recall  f1-score   support

         bad       0.61      0.48      0.54        29
         mid       0.67      0.36      0.47        33
        good       0.08      0.40      0.13         5

    accuracy                           0.42        67
   macro avg       0.45      0.42      0.38        67
weighted avg       0.60      0.42      0.47        67

[[ 1  0  2]
 [ 0 20  2]
 [ 0  1  0]]
              precision    recall  f1-score   support

         bad       1.00      0.33      0.50         3
         mid       0.95      0.91      0.93        22
 

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

              precision    recall  f1-score   support

         bad       1.00      1.00      1.00         2
         mid       0.95      1.00      0.97        18
        good       0.00      0.00      0.00         1

    accuracy                           0.95        21
   macro avg       0.65      0.67      0.66        21
weighted avg       0.91      0.95      0.93        21

[[ 3  1  1]
 [10 18  3]
 [ 5  0  1]]
              precision    recall  f1-score   support

         bad       0.17      0.60      0.26         5
         mid       0.95      0.58      0.72        31
        good       0.20      0.17      0.18         6

    accuracy                           0.52        42
   macro avg       0.44      0.45      0.39        42
weighted avg       0.75      0.52      0.59        42

[[ 5  9 12]
 [10 16 14]
 [ 4  3 12]]
              precision    recall  f1-score   support

         bad       0.26      0.19      0.22        26
         mid       0.57      0.40      0.47        40
 

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

[[48 14  3]
 [19 18  1]
 [ 4  1  0]]
              precision    recall  f1-score   support

         bad       0.68      0.74      0.71        65
         mid       0.55      0.47      0.51        38
        good       0.00      0.00      0.00         5

    accuracy                           0.61       108
   macro avg       0.41      0.40      0.40       108
weighted avg       0.60      0.61      0.60       108

[[ 1  1  2]
 [ 0 10 16]
 [ 0  2  5]]
              precision    recall  f1-score   support

         bad       1.00      0.25      0.40         4
         mid       0.77      0.38      0.51        26
        good       0.22      0.71      0.33         7

    accuracy                           0.43        37
   macro avg       0.66      0.45      0.42        37
weighted avg       0.69      0.43      0.47        37

[[0 2 1]
 [1 3 4]
 [3 3 3]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         3
         mid       0.38    

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is

[[ 5  6  0]
 [ 3 14  1]
 [ 1  0  0]]
              precision    recall  f1-score   support

         bad       0.56      0.45      0.50        11
         mid       0.70      0.78      0.74        18
        good       0.00      0.00      0.00         1

    accuracy                           0.63        30
   macro avg       0.42      0.41      0.41        30
weighted avg       0.62      0.63      0.63        30

[[ 1  2  0]
 [ 0 21  0]
 [ 0  1  0]]
              precision    recall  f1-score   support

         bad       1.00      0.33      0.50         3
         mid       0.88      1.00      0.93        21
        good       0.00      0.00      0.00         1

    accuracy                           0.88        25
   macro avg       0.62      0.44      0.48        25
weighted avg       0.85      0.88      0.84        25

[[ 8  8  1]
 [ 1  9 10]
 [ 4  8  4]]
              precision    recall  f1-score   support

         bad       0.62      0.47      0.53        17
         mid      

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is

              precision    recall  f1-score   support

         bad       0.56      0.28      0.37        18
         mid       0.38      0.47      0.42        17
        good       0.00      0.00      0.00         2

    accuracy                           0.35        37
   macro avg       0.31      0.25      0.26        37
weighted avg       0.45      0.35      0.37        37

[[ 0  5  1]
 [ 0 29  8]
 [ 0 10  1]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         6
         mid       0.66      0.78      0.72        37
        good       0.10      0.09      0.10        11

    accuracy                           0.56        54
   macro avg       0.25      0.29      0.27        54
weighted avg       0.47      0.56      0.51        54

[[ 0  0  0]
 [ 0 56  0]
 [ 0  0  0]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         0
         mid       1.00      1.00      1.00        56
 

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         2
         mid       0.74      1.00      0.85        17
        good       0.00      0.00      0.00         5

    accuracy                           0.71        24
   macro avg       0.25      0.33      0.28        24
weighted avg       0.52      0.71      0.60        24

[[ 0  0  0]
 [ 0 62  0]
 [ 0  0  0]]
              precision    recall  f1-score   support

         bad       0.00      0.00      0.00         0
         mid       1.00      1.00      1.00        62
        good       0.00      0.00      0.00         0

    accuracy                           1.00        62
   macro avg       0.33      0.33      0.33        62
weighted avg       1.00      1.00      1.00        62

[[ 2  6  4]
 [ 2 14  9]
 [ 2 10  1]]
              precision    recall  f1-score   support

         bad       0.33      0.17      0.22        12
         mid       0.47      0.56      0.51        25
 

C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\82102\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is